version: '3'

services:
  nest-api:
    image: ms-digital-store
    restart: always
    container_name: nest-ms-digital-store
    ports:
      - '3000:3000'
  db:
    image: 'postgres:14.3'
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    container_name: ds_db
    volumes:
      - ./postgres:/var/lib/postgresql/data


